name: 02 - Workflow event

on:
  push:
  pull_request:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Show trigger
      run: echo "I've been trrigered by a ${{ github.event_name}} event."
